language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run build
deploy:
  provider: pages:git
  edge: true
  local_dir: build
  deploy_key: deploy_key
  cleanup: false
  on:
    all_branches: true
    repo: ModelOriented/Arena
before_install:
- add-apt-repository ppa:deadsnakes/ppa
- apt-get update
- apt-get -y install python3.8 python3.8-distutils
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.8 get-pip.py && rm get-pip.py
- python --version
before_deploy:
- openssl aes-256-cbc -K $encrypted_d496dfbd0e99_key -iv $encrypted_d496dfbd0e99_iv
  -in deploy_key.enc -out ./deploy_key -d
- chmod 600 ./deploy_key
- ssh -i ./deploy_key -T git@github.com 2>&1 | grep successful > /dev/null
- echo 'ssh -i ./deploy_key "$@"' > use_ssh.sh
- chmod +x use_ssh.sh
- export GIT_SSH="./use_ssh.sh"
- git clone --quiet --branch="gh-pages" --depth=1 "git@github.com:ModelOriented/Arena.git" repo
- mkdir -p repo/branch build
- cp -R repo/branch build/
- rm -rf build/branch/$TRAVIS_BRANCH
- cp -R dist build/branch/$TRAVIS_BRANCH
- cp -R build/branch/master/* build/
- mkdir -p build/branch/docs
- cp -R build/branch/docs build/
